services:
  db:
    image: postgres:17.2

    environment:
      - POSTGRES_DB=${POSTGRES_DB:?error}
      - POSTGRES_USER=${POSTGRES_USER:?error}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?error}

    ports:
      - "6543:5432"

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile

networks:
  public:
  private:
volumes:
  back-notused:
  db-data:
secrets:
  db-password:
    file: db/password.txt
