services:
  db:
    image: postgres:17.2

    environment:
      - POSTGRES_DB=${POSTGRES_DB:?app}
      - POSTGRES_USER=${POSTGRES_USER:?postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?postgres}

    ports:
      - "6543:5432"

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    environment:
      - PORT=3000
      - HOST=0.0.0.0
      - DB_HOST=db
      - DB_NAME=${POSTGRES_DB:?app}
      - DB_USER=${POSTGRES_USER:?postgres}
      - DB_DATABASE=${POSTGRES_DB:?app}
      - DB_PORT=5432
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "4200:4200"

networks:
  public:
  private:
volumes:
  back-notused:
  db-data:
secrets:
  db-password:
    file: db/password.txt
